import type { Metadata } from 'next';
import './globals.css';
import { Header } from './components/Header';
import { Footer } from './components/Footer';
import { ReduxProvider } from '@/lib/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col'>
        <ReduxProvider>
          <Header />
          <main className='flex flex-grow items-center justify-center'>
            {children}
          </main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
