import type { Metadata } from 'next';
import './globals.css';
import { ModalProvider } from './contexts/Modal/ModalContext';
import { Header } from './components/Header';
import { Footer } from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col'>
        <ModalProvider>
          <Header />
          <main className='flex flex-grow items-center justify-center'>
            {children}
          </main>
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
