import type { Metadata } from 'next';
import './globals.css';
import { ModalProvider } from './contexts/modals/auth/register/ModalContext';
import { ModalProductProvider } from './contexts/modals/product/create-product/ModalProductContext';
import { Header } from './components/Header';
import { Footer } from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Exportação separada para a viewport
export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col'>
        <ModalProductProvider>
          <ModalProvider>
            <Header />
            <main className='flex flex-grow items-center justify-center'>
              {children}
            </main>
            <Footer />
          </ModalProvider>
          
        </ModalProductProvider>
      </body>
    </html>
  );
}
